const mockSearchData = {
"currentPage": 1,
"numberOfPages": 1,
"totalResults": 16,
"data": [
{
"id": "EhR179",
"name": "Comrade",
"nameDisplay": "Comrade",
"description": "A robust offering of chocolate and coffee, made in collaboration with the Las Vegas Distillery's Whiskey on oak.",
"abv": "8",
"ibu": "55",
"availableId": 8,
"styleId": 43,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-07-17 15:20:24",
"updateDate": "2015-07-17 15:21:30",
"available": {
"id": 8,
"name": "Winter",
"description": "Available during the winter months."
},
"style": {
"id": 43,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "American-Style Imperial Stout",
"shortName": "American Imperial Stout",
"description": "Black in color, American-style imperial stouts typically have a high alcohol content. Generally characterized as very robust. The extremely rich malty flavor and aroma are balanced with assertive hopping and fruity-ester characteristics. Bitterness should be moderately high to very high and balanced with full sweet malt character. Roasted malt astringency and bitterness can be moderately perceived but should not overwhelm the overall character. Hop aroma is usually moderately-high to overwhelmingly hop-floral, -citrus or -herbal. Diacetyl (butterscotch) levels should be absent.",
"ibuMin": "50",
"ibuMax": "80",
"abvMin": "7",
"abvMax": "12",
"srmMin": "40",
"srmMax": "40",
"ogMin": "1.08",
"fgMin": "1.02",
"fgMax": "1.03",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:28:49"
},
"type": "beer"
},
{
"id": "D2CTHU",
"name": "Comrade Brewing Company",
"nameShortDisplay": "Comrade",
"description": "Welkome to the Party.  That's the motto for Comrade Brewing Company in southeast Denver.  Comrade features back-to-basics beers and a tongue-in-cheek nod to Communism.  But the name actually celebrates the camaraderie the craft brewing industry has become known for.",
"website": "http://www.comradebrewing.com/",
"established": "2014",
"isOrganic": "N",
"images": {
"icon": "https://s3.amazonaws.com/brewerydbapi/brewery/D2CTHU/upload_d4qx2I-icon.png",
"medium": "https://s3.amazonaws.com/brewerydbapi/brewery/D2CTHU/upload_d4qx2I-medium.png",
"large": "https://s3.amazonaws.com/brewerydbapi/brewery/D2CTHU/upload_d4qx2I-large.png",
"squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/D2CTHU/upload_d4qx2I-squareMedium.png",
"squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/D2CTHU/upload_d4qx2I-squareLarge.png"
},
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-04-21 05:21:53",
"updateDate": "2015-12-22 15:53:48",
"isMassOwned": "N",
"brandClassification": "craft",
"type": "brewery"
},
{
"id": "dUPsdo",
"name": "Comrade Otter",
"nameDisplay": "Comrade Otter",
"description": "Our imperial chocolate stout has a mild, grassy hop aroma, with evident coffee and chocolate overtones. There is a smooth, slightly bitter, dark chocolate finish.",
"abv": "11.1",
"ibu": "41.4",
"styleId": 43,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-22 22:35:02",
"updateDate": "2015-06-23 12:47:43",
"style": {
"id": 43,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "American-Style Imperial Stout",
"shortName": "American Imperial Stout",
"description": "Black in color, American-style imperial stouts typically have a high alcohol content. Generally characterized as very robust. The extremely rich malty flavor and aroma are balanced with assertive hopping and fruity-ester characteristics. Bitterness should be moderately high to very high and balanced with full sweet malt character. Roasted malt astringency and bitterness can be moderately perceived but should not overwhelm the overall character. Hop aroma is usually moderately-high to overwhelmingly hop-floral, -citrus or -herbal. Diacetyl (butterscotch) levels should be absent.",
"ibuMin": "50",
"ibuMax": "80",
"abvMin": "7",
"abvMax": "12",
"srmMin": "40",
"srmMax": "40",
"ogMin": "1.08",
"fgMin": "1.02",
"fgMax": "1.03",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:28:49"
},
"type": "beer"
},
{
"id": "VxM7fs",
"name": "Comrade Bashleigh",
"nameDisplay": "Comrade Bashleigh",
"description": "German wheat beer made with Weyermann Pilsner and Weyerrmann Wheat Malt in collaboration with Bill Eye & Ashleigh Carter of the upcoming Bierstadt Lagerhaus in Denver, CO. Fermented with a special yeast strain from Schönram, Germany, the first time this yeast has been used in the US. Huge banana and bubblegum in the aroma with very subdued clove notes. Pours a lightly cloudy golden straw color with a dense white head.",
"abv": "5.2",
"ibu": "12",
"availableId": 4,
"styleId": 48,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-09-10 14:34:41",
"updateDate": "2014-09-11 19:39:11",
"available": {
"id": 4,
"name": "Seasonal",
"description": "Available at the same time of year, every year."
},
"style": {
"id": 48,
"categoryId": 4,
"category": {
"id": 4,
"name": "German Origin Ales",
"createDate": "2012-03-21 20:06:46"
},
"name": "South German-Style Hefeweizen / Hefeweissbier",
"shortName": "Hefeweizen",
"description": "The aroma and flavor of a Weissbier with yeast is decidedly fruity and phenolic. The phenolic characteristics are often described as clove-, nutmeg-like, mildly smoke-like or even vanilla-like. Banana-like esters should be present at low to medium-high levels. These beers are made with at least 50 percent malted wheat, and hop rates are quite low. Hop flavor and aroma are absent or present at very low levels. Weissbier is well attenuated and very highly carbonated and a medium to full bodied beer. The color is very pale to pale amber. Because yeast is present, the beer will have yeast flavor and a characteristically fuller mouthfeel and may be appropriately very cloudy. No diacetyl should be perceived.",
"ibuMin": "10",
"ibuMax": "15",
"abvMin": "4.9",
"abvMax": "5.5",
"srmMin": "3",
"srmMax": "9",
"ogMin": "1.047",
"fgMin": "1.008",
"fgMax": "1.016",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:29:27"
},
"type": "beer"
},
{
"id": "thuovb",
"name": "Comrade Warmer",
"nameDisplay": "Comrade Warmer",
"description": "Our take on the classic Russian Imperial Stout. With a bit of coffee aroma up front, Comrade Warmer’s full-bodied cocoa and licorice flavor fades to a gentle alcohol warmth on the finish.",
"abv": "7.4",
"ibu": "50",
"availableId": 3,
"styleId": 16,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-03-06 21:41:10",
"updateDate": "2015-03-06 21:41:10",
"available": {
"id": 3,
"name": "Not Available",
"description": "Beer is not available."
},
"style": {
"id": 16,
"categoryId": 1,
"category": {
"id": 1,
"name": "British Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "British-Style Imperial Stout",
"shortName": "British Imperial Stout",
"description": "Dark copper to very dark brown, British-style imperial stouts typically have high alcohol content. The extremely rich malty flavor (often characterized as toffee-like or caramel-like) and aroma are balanced with medium hopping and high fruity-ester characteristics. Bitterness should be moderate and balanced with sweet malt character. The bitterness may be higher in the darker versions. Roasted malt astringency is very low or absent. Bitterness should not overwhelm the overall character. Hop aroma can be subtle to moderately hop-floral, -citrus or -herbal. Diacetyl (butterscotch) levels should be absent.",
"ibuMin": "45",
"ibuMax": "65",
"abvMin": "7",
"abvMax": "12",
"srmMin": "20",
"srmMax": "35",
"ogMin": "1.08",
"fgMin": "1.02",
"fgMax": "1.03",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:22:41"
},
"type": "beer"
},
{
"id": "I8vDvI",
"name": "Quit Stalin",
"nameDisplay": "Quit Stalin",
"description": "Russian Imperial Stout, brewed with Chinook, Azacca and a generous late addition of Centennial, this all malt beer pours pitch black with a dark tan head. Aroma of toffee and chocolate dominate, lightly sweet, full-bodied and smooth on the palate with a subtle smoky finish and just enough bitterness to balance out the malt sweetness.",
"abv": "10.5",
"ibu": "74",
"glasswareId": 8,
"availableId": 1,
"styleId": 43,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2016-07-24 00:18:37",
"updateDate": "2016-08-23 18:35:41",
"glass": {
"id": 8,
"name": "Tulip",
"createDate": "2012-01-03 02:41:33"
},
"available": {
"id": 1,
"name": "Year Round",
"description": "Available year round as a staple beer."
},
"style": {
"id": 43,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "American-Style Imperial Stout",
"shortName": "American Imperial Stout",
"description": "Black in color, American-style imperial stouts typically have a high alcohol content. Generally characterized as very robust. The extremely rich malty flavor and aroma are balanced with assertive hopping and fruity-ester characteristics. Bitterness should be moderately high to very high and balanced with full sweet malt character. Roasted malt astringency and bitterness can be moderately perceived but should not overwhelm the overall character. Hop aroma is usually moderately-high to overwhelmingly hop-floral, -citrus or -herbal. Diacetyl (butterscotch) levels should be absent.",
"ibuMin": "50",
"ibuMax": "80",
"abvMin": "7",
"abvMax": "12",
"srmMin": "40",
"srmMax": "40",
"ogMin": "1.08",
"fgMin": "1.02",
"fgMax": "1.03",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:28:49"
},
"type": "beer"
},
{
"id": "p3V0Kk",
"name": "Honeyman IPA",
"nameDisplay": "Honeyman IPA",
"abv": "5.6",
"styleId": 73,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-18 16:23:16",
"updateDate": "2015-06-18 17:18:48",
"style": {
"id": 73,
"categoryId": 6,
"category": {
"id": 6,
"name": "International Ale Styles",
"createDate": "2012-03-21 20:06:46"
},
"name": "International-Style Pale Ale",
"shortName": "International Pale",
"description": "International-style pale ales range from deep golden to copper in color. The style is characterized by wide range of hop characters unlike fruity, floral and citrus-like American-variety hop character and unlike earthy, herbal English-variety hop character. Moderate to high hop bitterness, flavor, and aroma is evident. International pale ales have medium body and low to medium maltiness. Low caramel character is allowable. Fruity-ester flavor and aroma should be moderate to strong. Diacetyl should be absent or present at very low levels. Chill haze is allowable at cold temperatures.",
"ibuMin": "30",
"ibuMax": "42",
"abvMin": "4.5",
"abvMax": "5.5",
"srmMin": "6",
"srmMax": "14",
"ogMin": "1.044",
"fgMin": "1.008",
"fgMax": "1.014",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:35:08"
},
"type": "beer"
},
{
"id": "CjmCBJ",
"name": "Yellow Fever",
"nameDisplay": "Yellow Fever",
"abv": "5.5",
"styleId": 168,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-18 16:23:00",
"updateDate": "2015-06-18 17:18:45",
"style": {
"id": 168,
"categoryId": 11,
"category": {
"id": 11,
"name": "Hybrid/mixed Beer",
"createDate": "2012-03-21 20:06:46"
},
"name": "Chili Pepper Beer",
"shortName": "Chili Beer",
"description": "Chili Pepper Beers are any range of color from pale to very dark depending on the underlying style. Clear or hazy beer is acceptable in appearance. Chili Beers are any beers using chili peppers as a flavor, aroma or “heat” inducing adjunct to create distinct and balanced (ranging from subtle to intense) character. Chili pepper aromas ranging from subtle to intense may or may not be evident, and should not be overpowered by hop aromas. Malt sweetness can vary from very low to medium-high levels, depending on the underlying beer style. Hop bitterness is very low to medium-high. Chili pepper aroma and flavor qualities should not be overpowered by hop aroma and flavor, and should be present in harmony with characteristics typical of the underlying beer style. Chili pepper qualities may vary widely as vegetal, spicy or heat inducing flavors and/or aromas.",
"createDate": "2015-04-07 17:17:16"
},
"type": "beer"
},
{
"id": "aQ3O1s",
"name": "Moneypenny",
"nameDisplay": "Moneypenny",
"abv": "5.2",
"styleId": 6,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-18 16:22:35",
"updateDate": "2015-06-18 17:18:44",
"style": {
"id": 6,
"categoryId": 1,
"category": {
"id": 1,
"name": "British Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "English-Style Summer Ale",
"shortName": "English Summer Ale",
"description": "English Summer Ale is light straw to golden colored with medium-low to medium bitterness, light to medium-light body, and low to medium residual malt sweetness. Torrefied and/or malted wheat are often used in quantities of 25% or less. Malt flavor may be biscuit-like. English, American or Noble-type hop, character, flavor and aroma are evident and may or may not be assertive yet always well balanced with malt character. Mild carbonation traditionally characterizes draft-cask versions. In bottled versions, normal or lively carbon dioxide content is appropriate. The overall impression is refreshing and thirst quenching. Fruity-ester characters are acceptable at low to moderate levels. No butterscotch-like diacetyl or sweet corn-like dimethylsulfide (DMS) should be apparent in aroma or flavor. Chill haze is allowable at cold temperatures.",
"ibuMin": "20",
"ibuMax": "30",
"abvMin": "3.6",
"abvMax": "5",
"srmMin": "4",
"srmMax": "7",
"ogMin": "1.036",
"fgMin": "1.006",
"fgMax": "1.012",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:19:26"
},
"type": "beer"
},
{
"id": "KjFJdG",
"name": "Yellow Card American Blonde",
"nameDisplay": "Yellow Card American Blonde",
"description": "Crisp and refreshing blonde ale brewed with Mount Hood, Golding and Citra hops. Subtle notes of melon, passion fruit and lime in the aroma. A real thirst quencher",
"abv": "6",
"availableId": 1,
"styleId": 36,
"isOrganic": "Y",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-10 22:39:47",
"updateDate": "2015-06-10 22:39:47",
"available": {
"id": 1,
"name": "Year Round",
"description": "Available year round as a staple beer."
},
"style": {
"id": 36,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Golden or Blonde Ale",
"shortName": "Blonde",
"description": "Golden or Blonde ales are straw to golden blonde in color. They have a crisp, dry palate, light to medium body, and light malt sweetness. Low to medium hop aroma may be present but does not dominate. Bitterness is low to medium. Fruity esters may be perceived but do not predominate. Diacetyl should not be perceived. Chill haze should be absent.",
"ibuMin": "15",
"ibuMax": "25",
"abvMin": "4",
"abvMax": "5",
"srmMin": "3",
"srmMax": "7",
"ogMin": "1.045",
"fgMin": "1.008",
"fgMax": "1.016",
"createDate": "2012-03-21 20:06:46",
"updateDate": "2015-04-07 15:27:26"
},
"type": "beer"
},
{
"id": "iPWVTp",
"name": "Red IPA",
"nameDisplay": "Red IPA",
"description": "We wanted the Citra, Simcoe, Chinook and Millennium hops to shine in this Red IPA. Free of any crystal malt, still has a beautiful deep ruby color with minimal malt profile and no caramel sweetness or flavors generally associated with beers of this color.",
"abv": "6.1",
"ibu": "52",
"availableId": 4,
"styleId": 22,
"isOrganic": "Y",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-10 22:38:11",
"updateDate": "2015-06-18 17:16:27",
"available": {
"id": 4,
"name": "Seasonal",
"description": "Available at the same time of year, every year."
},
"style": {
"id": 22,
"categoryId": 2,
"category": {
"id": 2,
"name": "Irish Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Irish-Style Red Ale",
"shortName": "Irish Red",
"description": "Irish-style red ales range from light red-amber-copper to light brown in color. These ales have a medium hop bitterness and flavor. They often don't have hop aroma. Irish-style red ales have low to medium candy-like caramel malt sweetness and may have a balanced subtle degree of roast barley or roast malt character and complexity.  Irish-style Red Ales have a medium body. The style may have low levels of fruity-ester flavor and aroma. Diacetyl should be absent or at very low levels. Chill haze is allowable at cold temperatures. Slight yeast haze is acceptable for bottle-conditioned products.",
"ibuMin": "20",
"ibuMax": "28",
"abvMin": "4",
"abvMax": "4.5",
"srmMin": "11",
"srmMax": "18",
"ogMin": "1.04",
"fgMin": "1.01",
"fgMax": "1.014",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:23:38"
},
"type": "beer"
},
{
"id": "NMtLEy",
"name": "1659 Irish Dry Stout",
"nameDisplay": "1659 Irish Dry Stout",
"description": "Irish Dry Stout. Brewed with Irish Stout Malt from the Malting Company of Ireland, Simpsons DRC™ and Crisp Roasted Barley. Sessionable Stout for St. Patrick’s Day!",
"abv": "4.8",
"availableId": 4,
"styleId": 23,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2015-06-10 01:52:27",
"updateDate": "2015-06-10 22:35:55",
"available": {
"id": 4,
"name": "Seasonal",
"description": "Available at the same time of year, every year."
},
"style": {
"id": 23,
"categoryId": 2,
"category": {
"id": 2,
"name": "Irish Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Classic Irish-Style Dry Stout",
"shortName": "Dry Irish Stout",
"description": "Dry stouts have an initial malt and light caramel flavor profile with a distinctive dry-roasted bitterness in the finish. Dry stouts achieve a dry-roasted character through the use of roasted barley. The emphasis of coffee-like roasted barley and a moderate degree of roasted malt aromas define much of the character. Some slight acidity may be perceived but is not necessary. European hop aroma and flavor should be low or not perceived. Dry stouts have medium-light to medium body. Fruity esters are minimal and overshadowed by malt, high hop bitterness, and roasted barley character. Diacetyl (butterscotch) should be very low or not perceived. Head retention and rich character should be part of its visual character.",
"ibuMin": "30",
"ibuMax": "40",
"abvMin": "3.8",
"abvMax": "5",
"srmMin": "40",
"srmMax": "40",
"ogMin": "1.038",
"fgMin": "1.008",
"fgMax": "1.012",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:23:51"
},
"type": "beer"
},
{
"id": "tddJWR",
"name": "Koffee Kream Stout",
"nameDisplay": "Koffee Kream Stout",
"description": "Milk stout with coffee. This cream stout pours pitch black, but don't let that fool you. Massive coffee aroma yet full-bodied and sweet with a generous dose of milk sugar. We are the first Colorado brewery to use coffee from Kaladi Coffee Roasters, with a special custom roast, available only to Comrade Brewing Company.",
"abv": "4.8",
"ibu": "30",
"availableId": 1,
"styleId": 20,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-09-10 14:28:11",
"updateDate": "2014-09-11 15:45:00",
"available": {
"id": 1,
"name": "Year Round",
"description": "Available year round as a staple beer."
},
"style": {
"id": 20,
"categoryId": 1,
"category": {
"id": 1,
"name": "British Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Sweet or Cream Stout",
"shortName": "Sweet Stout",
"description": "Sweet stouts, also referred to as cream stouts, have less roasted bitter flavor and a full-bodied mouthfeel. The style can be given more body with milk sugar (lactose) before bottling. Malt sweetness, chocolate, and caramel flavor should dominate the flavor profile and contribute to the aroma. Hops should balance and suppress some of the sweetness without contributing apparent flavor or aroma. The overall impression should be sweet and full-bodied.",
"ibuMin": "15",
"ibuMax": "25",
"abvMin": "3",
"abvMax": "6",
"srmMin": "40",
"srmMax": "40",
"ogMin": "1.045",
"fgMin": "1.012",
"fgMax": "1.02",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:24:41"
},
"type": "beer"
},
{
"id": "HJuVN0",
"name": "Superpower IPA",
"nameDisplay": "Superpower IPA",
"description": "India Pale Ale with loads of Pacific Northwest hops. Huge pint and grapefruit hop aroma, with flavors of citrus, balanced bitterness with a light malt character. Pours a brilliant gold with a dense white head.",
"abv": "7.5",
"ibu": "100",
"srmId": 9,
"availableId": 1,
"styleId": 30,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-09-10 14:24:34",
"updateDate": "2015-04-19 19:49:37",
"srm": {
"id": 9,
"name": "9",
"hex": "E58500"
},
"available": {
"id": 1,
"name": "Year Round",
"description": "Available year round as a staple beer."
},
"style": {
"id": 30,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "American-Style India Pale Ale",
"shortName": "American IPA",
"description": "American-style India pale ales are perceived to have medium-high to intense hop bitterness, flavor and aroma with medium-high alcohol content. The style is further characterized by floral, fruity, citrus-like, piney, resinous, or sulfur-like American-variety hop character. Note that one or more of these American-variety hop characters is the perceived end, but the hop characters may be a result of the skillful use of hops of other national origins. The use of water with high mineral content results in a crisp, dry beer. This pale gold to deep copper-colored ale has a full, flowery hop aroma and may have a strong hop flavor (in addition to the perception of hop bitterness). India pale ales possess medium maltiness which contributes to a medium body. Fruity-ester flavors and aromas are moderate to very strong. Diacetyl can be absent or may be perceived at very low levels. Chill and/or hop haze is allowable at cold temperatures. (English and citrus-like American hops are considered enough of a distinction justifying separate American-style IPA and English-style IPA categories or subcategories. Hops of other origins may be used for bitterness or approximating traditional American or English character. See English-style India Pale Ale",
"ibuMin": "50",
"ibuMax": "70",
"abvMin": "6.3",
"abvMax": "7.5",
"srmMin": "6",
"srmMax": "14",
"ogMin": "1.06",
"fgMin": "1.012",
"fgMax": "1.018",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:26:37"
},
"type": "beer"
},
{
"id": "f0BhDZ",
"name": "DEFCON Red",
"nameDisplay": "DEFCON Red",
"description": "Our take on the Irish Red Ale. Brewed with Chinook, Golding and Cascade hops. Slight caramel sweetness, just a hint of chocolate and a light citrus nose. Pours a brilliant ruby color with a dense light tan white head.",
"abv": "5.2",
"ibu": "25",
"availableId": 1,
"styleId": 22,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-09-10 14:23:27",
"updateDate": "2014-09-11 18:04:27",
"available": {
"id": 1,
"name": "Year Round",
"description": "Available year round as a staple beer."
},
"style": {
"id": 22,
"categoryId": 2,
"category": {
"id": 2,
"name": "Irish Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Irish-Style Red Ale",
"shortName": "Irish Red",
"description": "Irish-style red ales range from light red-amber-copper to light brown in color. These ales have a medium hop bitterness and flavor. They often don't have hop aroma. Irish-style red ales have low to medium candy-like caramel malt sweetness and may have a balanced subtle degree of roast barley or roast malt character and complexity.  Irish-style Red Ales have a medium body. The style may have low levels of fruity-ester flavor and aroma. Diacetyl should be absent or at very low levels. Chill haze is allowable at cold temperatures. Slight yeast haze is acceptable for bottle-conditioned products.",
"ibuMin": "20",
"ibuMax": "28",
"abvMin": "4",
"abvMax": "4.5",
"srmMin": "11",
"srmMax": "18",
"ogMin": "1.04",
"fgMin": "1.01",
"fgMax": "1.014",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:23:38"
},
"type": "beer"
},
{
"id": "SoSaR7",
"name": "Fresh Hop Superpower IPA",
"nameDisplay": "Fresh Hop Superpower IPA",
"description": "Our Superpower India Pale Ale with 200 pounds of wet Chinook and 200 pounds of wet Cascade hops, delivered in less than 24 hours from the Western Slope of Colorado.",
"abv": "6.9",
"ibu": "100",
"availableId": 4,
"styleId": 26,
"isOrganic": "N",
"status": "verified",
"statusDisplay": "Verified",
"createDate": "2014-09-10 16:02:59",
"updateDate": "2014-09-10 18:45:09",
"available": {
"id": 4,
"name": "Seasonal",
"description": "Available at the same time of year, every year."
},
"style": {
"id": 26,
"categoryId": 3,
"category": {
"id": 3,
"name": "North American Origin Ales",
"createDate": "2012-03-21 20:06:45"
},
"name": "Fresh Wet Hop Ale",
"shortName": "Wet Hop Ale",
"description": "Any style of ale can be made into a fresh hop or wet hop version. These ales are hopped predominantly with fresh (newly harvested and kilned) and/or undried (“wet”) hops. These beers will exhibit especially aromas and flavors of green, almost chlorophyll-like or other fresh hop characters, in harmony with the characters of the base style of the beer. These beers may be aged and enjoyed after the initial “fresh-hop” character diminishes. Unique character from “aged” fresh hop beers may emerge, but they have yet to be defined.",
"createDate": "2012-03-21 20:06:45",
"updateDate": "2015-04-07 15:25:25"
},
"type": "beer"
}
],
"status": "success"
}

export default mockSearchData;
